### ISSUE TITLE
Global update

### ISSUE THREAD

**Issue by HighError** [Eviloma/eviloma-family#1]
Old repo: https://github.com/HighError/eviloma-family
Telegram bot repo: https://github.com/M1dDler/FamilyDashBoard

## Tasks:
- [x] New UI
  - [x] #6
  - [x] Main dashboard page UI (https://github.com/Eviloma/eviloma-family/commit/722afec04ffd96cb95c51253179fcb105b9ab535)
  - [x] #7
  - [x] Admin UI
    - [x] #9
    - [x] #10
    - [x] #11
    - [x] #12
    - [x] #13
- [x] Database
    - [x] #2
    - [x] #14
    - [x] #15
- [x] Telegram Bot
  - [x] #16
  - [x] Show information about linked telegram user 
    - [x] Bot
    - [x] #17 (web)
  - [x] #18
  - [x] #19
- [x] Misc
  - [x] #4
  - [x] #5
  - [x] Typesafe .env (https://github.com/Eviloma/eviloma-family/commit/89828de6206fa4bc2ec3095eecd6847d08541712)
